#!/bin/sh

# Part 1 - Assign all staged files to a variable:
# This variable will contain the files, which the developer is about to commit.
# This is needed as all files with changes might not be staged.
stagedFiles=$(git diff --staged --name-only)

# Part 2 - Apply the formatting and run fast tests:
# This is the part where files might be altered during the formatting.
# You could also run other plugin in addition to the formatting.
echo "Running spotlessApply..."
./gradlew spotlessApply test -DexcludeSlowTests=true
status=$? # store status from spotlessApply and test

# Part 3 - Re-add staged files:
# All files that were identified in Part 1 are staged with git add.
# A test is needed to check if the file exists, as a staged file might have been deleted.
for file in $stagedFiles; do
  if test -f "$file"; then
    git add $file
  fi
done

exit $status