name: GitHub Actions Demo - PRE
run-name: Testing commit message, ${{ github.event.head_commit.message }}

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  call-reusable-workflow:
    uses: ./.github/workflows/reusable-github-actions-demo.yml
    with:
      ENV: pre
      TEST_INPUT: Fake Test Input 2 PRE
    secrets: inherit