name: GitHub Actions Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-cache:
    concurrency: create-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "Triggered by commit [${{ vars.GITHUB_SHA }}]"

      - name: Create directories
        run: mkdir ./roo && mkdir ./roo/bar && mkdir ./roo/bar/foo

      - name: Create files
        run: echo "File Content" > ./roo/bar/foo/file1.txt
          && echo "File Content" > ./roo/bar/foo/file2.txt
          && echo "File Content" > ./roo/bar/foo/file3.txt

      - name: Log cache contents
        run: ls ./roo/bar/foo

      - name: Save Cache
        id: cache-roo
        uses: actions/cache@v3
        with:
          key: my-roo
          path: ./roo/bar/foo

  use-cache-1:
    needs: [create-cache]
    environment: dev
    concurrency: use-cache-1
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        id: cache-roo
        uses: actions/cache@v3
        with:
          key: my-roo
          path: ./roo/bar/foo

      - name: Log cache contents
#        if: steps.cache-roo.outputs.cache-hit != 'true'
        run: ls ./roo/bar/foo

  use-cache-2:
    needs: [create-cache]
    environment: dev
    concurrency: use-cache-2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        id: cache-roo
        uses: actions/cache@v3
        with:
          key: my-roo
          path: ./roo/bar/foo

      - name: Log cache contents
        #        if: steps.cache-roo.outputs.cache-hit != 'true'
        run: ls ./roo/bar/foo

  remove-cache:
    needs: [use-cache-1,use-cache-2]
    concurrency: create-cache
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3

      - name: Install gh-actions-cache extension
        run:  gh extension install actions/gh-actions-cache

      - name: Delete cache
        run: gh actions-cache delete my-roo --confirm