name: GitHub Actions Artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  save-artifact:
    concurrency: save-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - run: echo "Triggered by commit [${{ github.sha }}]"

      - name: Save `Commit SHA` as artifact
        env:
          GH_SHA: ${{ github.sha }}
        run: |
          mkdir -p ./foo
          echo $GH_SHA > ./foo/commit_sha

      - uses: actions/upload-artifact@v3
        with:
          name: commit_sha
          path: foo/

  use-artifact:
    concurrency: save-artifact
    needs: save-artifact
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/download-artifact@v3
        with:
          name: commit_sha

      - run: echo "commit_sha=$(cat commit_sha)" >> $GITHUB_ENV

      - run: echo "Environment Variable `Commit SHA` populated using artifact, value ${{ env.commit_sha }}"