name: API Gateway Test

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

#      - name: Configure AWS Credentials
#        uses: aws-actions/configure-aws-credentials@v1
#        with:
#          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/tester
          aws-region: ${{ secrets.AWS_REGION }}

#      - name: Deploy API Gateway
#        run: aws apigateway create-deployment --rest-api-id <your-api-id> --stage-name <your-stage>

      - name: Run API Tests (curl)
        run: |
          # Example using curl
          curl -X GET https://${{ secrets.APIGW_URL }}/prod/

      - name: Run API Tests (cli)
        run: aws apigateway test-invoke-method --rest-api-id ${{ secrets.AWS_API_ID }} --resource-id ${{ secrets.AWS_RESOURCE_ID }} --http-method GET --path-with-query-string '/'

#      - name: Clean Up
#        run: aws apigateway delete-deployment --rest-api-id <your-api-id> --deployment-id <deployment-id>