name: GitHub Actions Cache

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  create-cache:
    concurrency: create-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create directories
        run: mkdir ./roo && mkdir ./roo/bar && mkdir ./roo/bar/foo

      - name: Create files
        run: echo "File Content" > ./roo/bar/foo/file1.txt
          && echo "File Content" > ./roo/bar/foo/file2.txt
          && echo "File Content" > ./roo/bar/foo/file3.txt

      - name: Log cache contents
        run: ls ./roo/bar/foo

      - name: Save Cache
        id: cache-roo-${{github.run_number}}
        uses: actions/cache@v3
        with:
          key: my-roo-${{github.run_number}}
          path: ./roo

  use-cache-1:
    needs: [create-cache]
    environment: dev
    concurrency: create-cache
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        id: cache-roo-${{github.run_number}}
        uses: actions/cache@v3
        with:
          key: my-roo-${{github.run_number}}
          path: .

      - name: Log cache contents
        if: steps.cache-roo-${{github.run_number}}.outputs.cache-hit != 'true'
        run: ls .

  remove-cache:
    needs: [use-cache-1]
    concurrency: create-cache
    runs-on: ubuntu-latest
    steps:
      - name: Install gh-actions-cache extension
        run:  gh extension install actions/gh-actions-cache

      - name: Delete cache
        run: gh actions-cache delete my-roo-${{github.run_number}}