name: Kotlin Build and Test
run-name: build and test kotlin 🚀
on: [push]
jobs:
  kotlin-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: ./gradlew build
      - run: ./gradlew test
