name: Kotlin Build and Test
run-name: build and test kotlin 🚀

on:
  workflow_dispatch:

jobs:
  kotlin-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: fwilhe2/setup-kotlin@main

      - run: ./gradlew build
      - run: ./gradlew test
#      - run: ./gradlew sonarqube -Dsonar.projectKey=kotlin-github-actions-221014a -Dsonar.host.url=http://localhost:9000 -Dsonar.login=foo
#      - run: ./gradlew test jacocoTestReport sonarqube -Dsonar.projectKey=kotlin-github-actions-221014a -Dsonar.host.url=http://localhost:9000 -Dsonar.login=bar

      - name: Prepare artifacts
        run: mkdir ./build/myartifacts | find **/libs/*.jar | while read line ; do cp $line ./build/myartifacts/; done

      - name: Log Serverless Framework artifacts
        run: ls ./build/myartifacts/

      - name: Cache my artifacts
        id: cache-myartifacts
        uses: actions/cache@v3
        with:
          key: my-build-artifacts
          path: ./build/myartifacts/

  dev-store-build-artifacts:
    needs: [kotlin-build-test]
    environment: dev
    concurrency: build-service
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - uses: actions/checkout@v3

#      - name: Restore cache
#        id: cache-myartifacts
#        uses: actions/cache@v3
#        with:
#          key: my-build-artifacts
#          path: build

      - name: Log Serverless Framework artifacts
        if: steps.cache-myartifacts.outputs.cache-hit != 'true'
        run: ls ./build/myartifacts/
