name: Kotlin Build and Test
run-name: build and test kotlin 🚀

on:
  workflow_dispatch:

jobs:
  kotlin-build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: fwilhe2/setup-kotlin@main
      - run: ./gradlew build
      - run: ./gradlew test
#      - run: ./gradlew sonarqube -Dsonar.projectKey=kotlin-github-actions-221014a -Dsonar.host.url=http://localhost:9000 -Dsonar.login=foo
#      - run: ./gradlew test jacocoTestReport sonarqube -Dsonar.projectKey=kotlin-github-actions-221014a -Dsonar.host.url=http://localhost:9000 -Dsonar.login=bar
