name: Triggered by another workflow
run-name: Triggered by another workflow RT name

on:
  workflow_run:
    workflows: [GitHub Actions Artifact]
    types: [completed]
  workflow_dispatch:

jobs:
  Job-Triggered-By-Another-Workflow:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    environment: dev
    runs-on: ubuntu-latest
    steps:
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "Triggered by commit [${{ github.sha }}]"

      - run: echo "${{ github.event.workflow_run }}"

      - uses: actions/download-artifact@v3
        with:
          name: commit_sha

      - run: echo "commit_sha=$(cat commit_sha)" >> $GITHUB_ENV

      - run: echo "Environment Variable `Commit SHA` populated using artifact, value ${{ env.commit_sha }}"
